language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --no-interaction --dev

script: VERBOSE=true vendor/bin/tester tests/

deploy:
  provider: cloudcontrol
  email: leonard.odlozilik@gmail.com
  password:
    secure: lA2KcFFpyTWWutrlNFuL+EEhgIS2qRFre1aE+MF3TOGGpjeb9IdHth3YKGp9m7tutwxv5eoJTLImZtnUTKAU3zav/b2h74iFNYWOZ4YMWwSwA1wYBSSG2fSwyOYnEmlJL7OZQvRo+6e3ByMIn+Yk9hMVJrW6T8WUhXqEz880Rk0=
  deployment: nplayground/default
  on:
    repo: LeonardoCA/nplayground
