language: php
php:
- 5.4
- 5.5
- 5.6
- hhvm
matrix:
  fast_finish: true
  allow_failures:
  - php: hhvm
services:
  - redis-server
before_install: npm install -g bower && npm install -g grunt-cli
install: npm install && grunt build
before_script:
- "./.travis.redis.sh"
- composer self-update
- composer install --no-interaction --dev
- cp ./app/config/config.local.neon.example ./app/config/config.local.neon
- mysql -e 'create database nplayground;'
script:
- vendor/bin/tester tests -s -p php -c tests/php.ini-unix
after_failure:
- for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
